### ISSUE TITLE
Slow serial output speed

### ISSUE THREAD

**Issue by ecmjohnson** [sparkfun/SparkFun_ProDriver_TC78H670FTG_Arduino_Library#2]
I found that the serial output method that changes the pin mode to input to allow the pull up to driver the signal high was slower than simply writing the line high. That is, [this snippet](https://github.com/sparkfun/SparkFun_ProDriver_TC78H670FTG_Arduino_Library/blob/d056d389952dd4fb2e94a73efe3c1a89159aef1c/src/SparkFun_ProDriver_TC78H670FTG_Arduino_Library.cpp#L424-L431) would be much slower than a simple `digitalWrite` in both cases. I was seeing ~3ms to send a serial command compared to ~120us on the ESP32 RedBoard.

I'm wondering why the decision was made to use the pull up rather than a `digitalWrite` in both cases which would definitely be simpler? I don't see any impact in my application from switching to not use the on-board external pull-ups, but I'd like to understand this decision.

**Comment by lewispg228** [comment]
Hi @ecmjohnson ,
Thanks for submitting this. Your method of speeding up serial output seems like a valid idea for 3.3V microcontrollers. Could you please share your code?

The external pullups (and use of pinMode(INPUT)) were done in an effort to keep this compatible with 5V logic microcontrollers. If someone used a 5V micro and set it to output HIGH, then that would cause issues with the onboard pullups to 3.3V. 

It would be nice to offer the option to speed up serial (if the user is using a 3.3V microcontroller). Perhaps an additional advanced example with a #define at the top could select the mode. We will look into the possibility of writing this into the library.

Also, potentially changing the control method of the clock pin (as well) could speed this up even more.

We should be able to get some hardware together and do some testing over the next few days.

Let us know what you think and thanks again.

-Pete

**Comment by lewispg228** [comment]
@ecmjohnson We were able to test this out on some hardware: 

[mini stepper motor driver](https://www.sparkfun.com/products/25167)
[ESP32 C](https://www.sparkfun.com/products/20168)
[this stepper motor](https://www.sparkfun.com/products/10846) 

Indeed, changing to your method of only using digitalWrite() increases speed dramatically. We were able to go from 1.8ms to 55uS. See [this pull request](https://github.com/sparkfun/SparkFun_ProDriver_TC78H670FTG_Arduino_Library/pull/3) for details. We also created release v1.0.2. This update should show up in Arduino Library manager in a day or so.

![image](https://github.com/user-attachments/assets/20f21a4a-699a-4712-8a73-0c3e2defeb69)


Thanks!

Warning to all: Please only use fastSerialMode with 3.3V Logic level microcontrollers!
